2024-06-03 12:54:18,704 INFO    Thread-2 (_run_job):390404 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-06-03 12:54:18,704 INFO    Thread-2 (_run_job):390404 [wandb_setup.py:_flush():76] Configure stats pid to 390404
2024-06-03 12:54:18,704 INFO    Thread-2 (_run_job):390404 [wandb_setup.py:_flush():76] Loading settings from /home/test/.config/wandb/settings
2024-06-03 12:54:18,704 INFO    Thread-2 (_run_job):390404 [wandb_setup.py:_flush():76] Loading settings from /home/test/FRL/wandb/settings
2024-06-03 12:54:18,704 INFO    Thread-2 (_run_job):390404 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'mnist-conv2-my-attack-cosine', 'entity': 'griffith', 'root_dir': '/home/test/FRL', 'sweep_id': '0vgdpsor', 'run_id': 'f4q80nox', 'sweep_param_path': '/home/test/FRL/wandb/sweep-0vgdpsor/config-f4q80nox.yaml'}
2024-06-03 12:54:18,704 INFO    Thread-2 (_run_job):390404 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-03 12:54:18,704 INFO    Thread-2 (_run_job):390404 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': '/home/test/FRL/main.py', 'program': '/home/test/FRL/main.py'}
2024-06-03 12:54:18,704 INFO    Thread-2 (_run_job):390404 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-03 12:54:18,705 INFO    Thread-2 (_run_job):390404 [wandb_init.py:_log_setup():521] Logging user logs to /home/test/FRL/wandb/run-20240603_125418-f4q80nox/logs/debug.log
2024-06-03 12:54:18,705 INFO    Thread-2 (_run_job):390404 [wandb_init.py:_log_setup():522] Logging internal logs to /home/test/FRL/wandb/run-20240603_125418-f4q80nox/logs/debug-internal.log
2024-06-03 12:54:18,705 INFO    Thread-2 (_run_job):390404 [wandb_init.py:init():561] calling init triggers
2024-06-03 12:54:18,705 INFO    Thread-2 (_run_job):390404 [wandb_init.py:init():568] wandb.init called with sweep_config: {'iteration': 50, 'k': 0.1, 'lr': 0.001, 'm_r': 0.2, 'max_t': 2500, 'nep': 100, 'noise': 1, 'non_iid': 1, 'temp': 0.1}
config: {}
2024-06-03 12:54:18,705 INFO    Thread-2 (_run_job):390404 [wandb_init.py:init():606] wandb.init() called when a run is still active
2024-06-03 12:54:23,213 INFO    Thread-2 (_run_job):390404 [wandb_run.py:_finish():2064] finishing run griffith/mnist-conv2-my-attack-cosine/f4q80nox
2024-06-03 12:54:23,213 INFO    Thread-2 (_run_job):390404 [wandb_run.py:_atexit_cleanup():2304] got exitcode: 1
2024-06-03 12:54:23,213 INFO    Thread-2 (_run_job):390404 [wandb_run.py:_restore():2287] restore
2024-06-03 12:54:23,213 INFO    Thread-2 (_run_job):390404 [wandb_run.py:_restore():2293] restore done
2024-06-03 12:54:28,952 INFO    Thread-2 (_run_job):390404 [wandb_run.py:_footer_history_summary_info():3936] rendering history
2024-06-03 12:54:28,952 INFO    Thread-2 (_run_job):390404 [wandb_run.py:_footer_history_summary_info():3968] rendering summary
2024-06-03 12:54:28,955 INFO    Thread-2 (_run_job):390404 [wandb_run.py:_footer_sync_info():3895] logging synced files
2024-06-03 12:54:29,033 ERROR   MainThread:390404 [pyagent.py:_run_jobs_from_queue():236] Run f4q80nox errored:
Traceback (most recent call last):
  File "/home/test/anaconda3/envs/FRL_test/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 162, in __getattr__
    return self.__getitem__(key)
  File "/home/test/anaconda3/envs/FRL_test/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'mode'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/test/anaconda3/envs/FRL_test/lib/python3.10/site-packages/wandb/agents/pyagent.py", line 308, in _run_job
    self._function()
  File "/home/test/FRL/main.py", line 115, in main
    FRL_train_defense_val(tr_loaders, te_loader,val_loader)
  File "/home/test/FRL/FL_train.py", line 604, in FRL_train_defense_val
    selected_user_updates=defense.FRL_fang(FLmodel, user_updates,len(round_users),len(round_malicious),val_loader,criterion, args.device,initial_scores,mode=wandb.config.mode)
  File "/home/test/anaconda3/envs/FRL_test/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 164, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'mode'

2024-06-03 12:54:32,977 INFO    Thread-6 (_run_job):390404 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-06-03 12:54:32,977 INFO    Thread-6 (_run_job):390404 [wandb_setup.py:_flush():76] Configure stats pid to 390404
2024-06-03 12:54:32,977 INFO    Thread-6 (_run_job):390404 [wandb_setup.py:_flush():76] Loading settings from /home/test/.config/wandb/settings
2024-06-03 12:54:32,977 INFO    Thread-6 (_run_job):390404 [wandb_setup.py:_flush():76] Loading settings from /home/test/FRL/wandb/settings
2024-06-03 12:54:32,977 INFO    Thread-6 (_run_job):390404 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'mnist-conv2-my-attack-cosine', 'entity': 'griffith', 'root_dir': '/home/test/FRL', 'run_id': 'vp1oqmrv', 'sweep_param_path': '/home/test/FRL/wandb/sweep-0vgdpsor/config-vp1oqmrv.yaml', 'sweep_id': '0vgdpsor'}
2024-06-03 12:54:32,977 INFO    Thread-6 (_run_job):390404 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-03 12:54:32,977 INFO    Thread-6 (_run_job):390404 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': '/home/test/FRL/main.py', 'program': '/home/test/FRL/main.py'}
2024-06-03 12:54:32,977 INFO    Thread-6 (_run_job):390404 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-03 12:54:32,977 INFO    Thread-6 (_run_job):390404 [wandb_init.py:_log_setup():521] Logging user logs to /home/test/FRL/wandb/run-20240603_125432-vp1oqmrv/logs/debug.log
2024-06-03 12:54:32,977 INFO    Thread-6 (_run_job):390404 [wandb_init.py:_log_setup():522] Logging internal logs to /home/test/FRL/wandb/run-20240603_125432-vp1oqmrv/logs/debug-internal.log
2024-06-03 12:54:32,977 INFO    Thread-6 (_run_job):390404 [wandb_init.py:init():561] calling init triggers
2024-06-03 12:54:32,977 INFO    Thread-6 (_run_job):390404 [wandb_init.py:init():568] wandb.init called with sweep_config: {'iteration': 50, 'k': 0.1, 'lr': 0.001, 'm_r': 0.2, 'max_t': 2500, 'nep': 100, 'noise': 1, 'non_iid': 0.5, 'temp': 0.1}
config: {}
2024-06-03 12:54:32,977 INFO    Thread-6 (_run_job):390404 [wandb_init.py:init():611] starting backend
2024-06-03 12:54:32,977 INFO    Thread-6 (_run_job):390404 [wandb_init.py:init():615] setting up manager
2024-06-03 12:54:32,980 INFO    Thread-6 (_run_job):390404 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-06-03 12:54:32,980 INFO    Thread-6 (_run_job):390404 [wandb_init.py:init():623] backend started and connected
2024-06-03 12:54:32,985 INFO    Thread-6 (_run_job):390404 [wandb_run.py:_config_callback():1347] config_cb None None {'iteration': 50, 'k': 0.1, 'lr': 0.001, 'm_r': 0.2, 'max_t': 2500, 'nep': 100, 'noise': 1, 'non_iid': 0.5, 'temp': 0.1}
2024-06-03 12:54:32,985 INFO    Thread-6 (_run_job):390404 [wandb_init.py:init():715] updated telemetry
2024-06-03 12:54:32,988 INFO    Thread-6 (_run_job):390404 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-06-03 12:54:33,481 INFO    Thread-6 (_run_job):390404 [wandb_run.py:_on_init():2357] communicating current version
2024-06-03 12:54:33,585 INFO    Thread-6 (_run_job):390404 [wandb_run.py:_on_init():2366] got version response upgrade_message: "wandb version 0.17.0 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-06-03 12:54:33,585 INFO    Thread-6 (_run_job):390404 [wandb_init.py:init():799] starting run threads in backend
2024-06-03 12:54:35,141 INFO    Thread-6 (_run_job):390404 [wandb_run.py:_console_start():2335] atexit reg
2024-06-03 12:54:35,141 INFO    Thread-6 (_run_job):390404 [wandb_run.py:_redirect():2190] redirect: wrap_raw
2024-06-03 12:54:35,141 INFO    Thread-6 (_run_job):390404 [wandb_run.py:_redirect():2255] Wrapping output streams.
2024-06-03 12:54:35,142 INFO    Thread-6 (_run_job):390404 [wandb_run.py:_redirect():2280] Redirects installed.
2024-06-03 12:54:35,142 INFO    Thread-6 (_run_job):390404 [wandb_init.py:init():842] run started, returning control to user process
2024-06-03 12:54:35,214 INFO    Thread-6 (_run_job):390404 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-06-03 12:54:35,214 INFO    Thread-6 (_run_job):390404 [wandb_setup.py:_flush():76] Configure stats pid to 390404
2024-06-03 12:54:35,214 INFO    Thread-6 (_run_job):390404 [wandb_setup.py:_flush():76] Loading settings from /home/test/.config/wandb/settings
2024-06-03 12:54:35,214 INFO    Thread-6 (_run_job):390404 [wandb_setup.py:_flush():76] Loading settings from /home/test/FRL/wandb/settings
2024-06-03 12:54:35,214 INFO    Thread-6 (_run_job):390404 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'mnist-conv2-my-attack-cosine', 'entity': 'griffith', 'root_dir': '/home/test/FRL', 'run_id': 'vp1oqmrv', 'sweep_param_path': '/home/test/FRL/wandb/sweep-0vgdpsor/config-vp1oqmrv.yaml', 'sweep_id': '0vgdpsor'}
2024-06-03 12:54:35,214 INFO    Thread-6 (_run_job):390404 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-03 12:54:35,214 INFO    Thread-6 (_run_job):390404 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': '/home/test/FRL/main.py', 'program': '/home/test/FRL/main.py'}
2024-06-03 12:54:35,214 INFO    Thread-6 (_run_job):390404 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-03 12:54:35,214 INFO    Thread-6 (_run_job):390404 [wandb_init.py:_log_setup():521] Logging user logs to /home/test/FRL/wandb/run-20240603_125435-vp1oqmrv/logs/debug.log
2024-06-03 12:54:35,214 INFO    Thread-6 (_run_job):390404 [wandb_init.py:_log_setup():522] Logging internal logs to /home/test/FRL/wandb/run-20240603_125435-vp1oqmrv/logs/debug-internal.log
2024-06-03 12:54:35,214 INFO    Thread-6 (_run_job):390404 [wandb_init.py:init():561] calling init triggers
2024-06-03 12:54:35,214 INFO    Thread-6 (_run_job):390404 [wandb_init.py:init():568] wandb.init called with sweep_config: {'iteration': 50, 'k': 0.1, 'lr': 0.001, 'm_r': 0.2, 'max_t': 2500, 'nep': 100, 'noise': 1, 'non_iid': 0.5, 'temp': 0.1}
config: {}
2024-06-03 12:54:35,214 INFO    Thread-6 (_run_job):390404 [wandb_init.py:init():606] wandb.init() called when a run is still active
2024-06-03 12:54:38,341 INFO    Thread-6 (_run_job):390404 [wandb_run.py:_finish():2064] finishing run griffith/mnist-conv2-my-attack-cosine/vp1oqmrv
2024-06-03 12:54:38,341 INFO    Thread-6 (_run_job):390404 [wandb_run.py:_atexit_cleanup():2304] got exitcode: 1
2024-06-03 12:54:38,341 INFO    Thread-6 (_run_job):390404 [wandb_run.py:_restore():2287] restore
2024-06-03 12:54:38,341 INFO    Thread-6 (_run_job):390404 [wandb_run.py:_restore():2293] restore done
2024-06-03 12:54:43,033 INFO    Thread-6 (_run_job):390404 [wandb_run.py:_footer_history_summary_info():3936] rendering history
2024-06-03 12:54:43,034 INFO    Thread-6 (_run_job):390404 [wandb_run.py:_footer_history_summary_info():3968] rendering summary
2024-06-03 12:54:43,049 INFO    Thread-6 (_run_job):390404 [wandb_run.py:_footer_sync_info():3895] logging synced files
2024-06-03 12:54:43,073 ERROR   MainThread:390404 [pyagent.py:_run_jobs_from_queue():236] Run vp1oqmrv errored:
Traceback (most recent call last):
  File "/home/test/anaconda3/envs/FRL_test/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 162, in __getattr__
    return self.__getitem__(key)
  File "/home/test/anaconda3/envs/FRL_test/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'mode'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/test/anaconda3/envs/FRL_test/lib/python3.10/site-packages/wandb/agents/pyagent.py", line 308, in _run_job
    self._function()
  File "/home/test/FRL/main.py", line 115, in main
    FRL_train_defense_val(tr_loaders, te_loader,val_loader)
  File "/home/test/FRL/FL_train.py", line 604, in FRL_train_defense_val
    selected_user_updates=defense.FRL_fang(FLmodel, user_updates,len(round_users),len(round_malicious),val_loader,criterion, args.device,initial_scores,mode=wandb.config.mode)
  File "/home/test/anaconda3/envs/FRL_test/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 164, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'mode'

2024-06-03 12:54:48,994 INFO    Thread-9 (_run_job):390404 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-06-03 12:54:48,994 INFO    Thread-9 (_run_job):390404 [wandb_setup.py:_flush():76] Configure stats pid to 390404
2024-06-03 12:54:48,994 INFO    Thread-9 (_run_job):390404 [wandb_setup.py:_flush():76] Loading settings from /home/test/.config/wandb/settings
2024-06-03 12:54:48,994 INFO    Thread-9 (_run_job):390404 [wandb_setup.py:_flush():76] Loading settings from /home/test/FRL/wandb/settings
2024-06-03 12:54:48,994 INFO    Thread-9 (_run_job):390404 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'mnist-conv2-my-attack-cosine', 'entity': 'griffith', 'root_dir': '/home/test/FRL', 'run_id': '67ee5rd2', 'sweep_param_path': '/home/test/FRL/wandb/sweep-0vgdpsor/config-67ee5rd2.yaml', 'sweep_id': '0vgdpsor'}
2024-06-03 12:54:48,994 INFO    Thread-9 (_run_job):390404 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-03 12:54:48,994 INFO    Thread-9 (_run_job):390404 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': '/home/test/FRL/main.py', 'program': '/home/test/FRL/main.py'}
2024-06-03 12:54:48,994 INFO    Thread-9 (_run_job):390404 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-03 12:54:48,994 INFO    Thread-9 (_run_job):390404 [wandb_init.py:_log_setup():521] Logging user logs to /home/test/FRL/wandb/run-20240603_125448-67ee5rd2/logs/debug.log
2024-06-03 12:54:48,994 INFO    Thread-9 (_run_job):390404 [wandb_init.py:_log_setup():522] Logging internal logs to /home/test/FRL/wandb/run-20240603_125448-67ee5rd2/logs/debug-internal.log
2024-06-03 12:54:48,994 INFO    Thread-9 (_run_job):390404 [wandb_init.py:init():561] calling init triggers
2024-06-03 12:54:48,994 INFO    Thread-9 (_run_job):390404 [wandb_init.py:init():568] wandb.init called with sweep_config: {'iteration': 50, 'k': 0.1, 'lr': 0.001, 'm_r': 0, 'max_t': 2500, 'nep': 100, 'noise': 1, 'non_iid': 1, 'temp': 0.1}
config: {}
2024-06-03 12:54:48,994 INFO    Thread-9 (_run_job):390404 [wandb_init.py:init():611] starting backend
2024-06-03 12:54:48,994 INFO    Thread-9 (_run_job):390404 [wandb_init.py:init():615] setting up manager
2024-06-03 12:54:48,997 INFO    Thread-9 (_run_job):390404 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-06-03 12:54:48,997 INFO    Thread-9 (_run_job):390404 [wandb_init.py:init():623] backend started and connected
2024-06-03 12:54:49,002 INFO    Thread-9 (_run_job):390404 [wandb_run.py:_config_callback():1347] config_cb None None {'iteration': 50, 'k': 0.1, 'lr': 0.001, 'm_r': 0, 'max_t': 2500, 'nep': 100, 'noise': 1, 'non_iid': 1, 'temp': 0.1}
2024-06-03 12:54:49,002 INFO    Thread-9 (_run_job):390404 [wandb_init.py:init():715] updated telemetry
2024-06-03 12:54:49,005 INFO    Thread-9 (_run_job):390404 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-06-03 12:54:49,540 INFO    Thread-9 (_run_job):390404 [wandb_run.py:_on_init():2357] communicating current version
2024-06-03 12:54:49,642 INFO    Thread-9 (_run_job):390404 [wandb_run.py:_on_init():2366] got version response upgrade_message: "wandb version 0.17.0 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-06-03 12:54:49,643 INFO    Thread-9 (_run_job):390404 [wandb_init.py:init():799] starting run threads in backend
2024-06-03 12:54:51,133 INFO    Thread-9 (_run_job):390404 [wandb_run.py:_console_start():2335] atexit reg
2024-06-03 12:54:51,133 INFO    Thread-9 (_run_job):390404 [wandb_run.py:_redirect():2190] redirect: wrap_raw
2024-06-03 12:54:51,133 INFO    Thread-9 (_run_job):390404 [wandb_run.py:_redirect():2255] Wrapping output streams.
2024-06-03 12:54:51,133 INFO    Thread-9 (_run_job):390404 [wandb_run.py:_redirect():2280] Redirects installed.
2024-06-03 12:54:51,134 INFO    Thread-9 (_run_job):390404 [wandb_init.py:init():842] run started, returning control to user process
2024-06-03 12:54:51,212 INFO    Thread-9 (_run_job):390404 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-06-03 12:54:51,212 INFO    Thread-9 (_run_job):390404 [wandb_setup.py:_flush():76] Configure stats pid to 390404
2024-06-03 12:54:51,212 INFO    Thread-9 (_run_job):390404 [wandb_setup.py:_flush():76] Loading settings from /home/test/.config/wandb/settings
2024-06-03 12:54:51,212 INFO    Thread-9 (_run_job):390404 [wandb_setup.py:_flush():76] Loading settings from /home/test/FRL/wandb/settings
2024-06-03 12:54:51,212 INFO    Thread-9 (_run_job):390404 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'mnist-conv2-my-attack-cosine', 'entity': 'griffith', 'root_dir': '/home/test/FRL', 'run_id': '67ee5rd2', 'sweep_param_path': '/home/test/FRL/wandb/sweep-0vgdpsor/config-67ee5rd2.yaml', 'sweep_id': '0vgdpsor'}
2024-06-03 12:54:51,212 INFO    Thread-9 (_run_job):390404 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-03 12:54:51,212 INFO    Thread-9 (_run_job):390404 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': '/home/test/FRL/main.py', 'program': '/home/test/FRL/main.py'}
2024-06-03 12:54:51,212 INFO    Thread-9 (_run_job):390404 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-03 12:54:51,212 INFO    Thread-9 (_run_job):390404 [wandb_init.py:_log_setup():521] Logging user logs to /home/test/FRL/wandb/run-20240603_125451-67ee5rd2/logs/debug.log
2024-06-03 12:54:51,212 INFO    Thread-9 (_run_job):390404 [wandb_init.py:_log_setup():522] Logging internal logs to /home/test/FRL/wandb/run-20240603_125451-67ee5rd2/logs/debug-internal.log
2024-06-03 12:54:51,212 INFO    Thread-9 (_run_job):390404 [wandb_init.py:init():561] calling init triggers
2024-06-03 12:54:51,213 INFO    Thread-9 (_run_job):390404 [wandb_init.py:init():568] wandb.init called with sweep_config: {'iteration': 50, 'k': 0.1, 'lr': 0.001, 'm_r': 0, 'max_t': 2500, 'nep': 100, 'noise': 1, 'non_iid': 1, 'temp': 0.1}
config: {}
2024-06-03 12:54:51,213 INFO    Thread-9 (_run_job):390404 [wandb_init.py:init():606] wandb.init() called when a run is still active
2024-06-03 12:54:52,743 INFO    Thread-9 (_run_job):390404 [wandb_run.py:_finish():2064] finishing run griffith/mnist-conv2-my-attack-cosine/67ee5rd2
2024-06-03 12:54:52,743 INFO    Thread-9 (_run_job):390404 [wandb_run.py:_atexit_cleanup():2304] got exitcode: 1
2024-06-03 12:54:52,743 INFO    Thread-9 (_run_job):390404 [wandb_run.py:_restore():2287] restore
2024-06-03 12:54:52,743 INFO    Thread-9 (_run_job):390404 [wandb_run.py:_restore():2293] restore done
2024-06-03 12:54:56,469 INFO    Thread-9 (_run_job):390404 [wandb_run.py:_footer_history_summary_info():3936] rendering history
2024-06-03 12:54:56,469 INFO    Thread-9 (_run_job):390404 [wandb_run.py:_footer_history_summary_info():3968] rendering summary
2024-06-03 12:54:56,485 INFO    Thread-9 (_run_job):390404 [wandb_run.py:_footer_sync_info():3895] logging synced files
2024-06-03 12:54:56,511 ERROR   MainThread:390404 [pyagent.py:_run_jobs_from_queue():236] Run 67ee5rd2 errored:
Traceback (most recent call last):
  File "/home/test/anaconda3/envs/FRL_test/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 162, in __getattr__
    return self.__getitem__(key)
  File "/home/test/anaconda3/envs/FRL_test/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'mode'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/test/anaconda3/envs/FRL_test/lib/python3.10/site-packages/wandb/agents/pyagent.py", line 308, in _run_job
    self._function()
  File "/home/test/FRL/main.py", line 115, in main
    FRL_train_defense_val(tr_loaders, te_loader,val_loader)
  File "/home/test/FRL/FL_train.py", line 604, in FRL_train_defense_val
    selected_user_updates=defense.FRL_fang(FLmodel, user_updates,len(round_users),len(round_malicious),val_loader,criterion, args.device,initial_scores,mode=wandb.config.mode)
  File "/home/test/anaconda3/envs/FRL_test/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 164, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'mode'

2024-06-03 12:54:56,511 ERROR   MainThread:390404 [pyagent.py:_run_jobs_from_queue():247] Detected 3 failed runs in the first 60 seconds, killing sweep.
